name: Codecov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.9.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.12
    - name: Install dependencies
      run: |
        pip install pytest-cov
        pip install -r requirements.txt
        echo requirements installed
    - name: Run the tests
      run: |
          python ./UnitTests/database_connection_test.py
          python ./UnitTests/database_crud_test.py
          python ./UnitTests/database_tables_test.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: c0585880-a6f3-41f2-b1f6-4b5ce8e66266
      
